### ISSUE TITLE
undefined method `to_money' for 1:Fixnum

### ISSUE THREAD

**Issue by spundun** [RubyMoney/google_currency#30]
Hi from the README.md file. I tried to run the whole usage code and it gives me this error.

 
1.001.00test.rb:22:in `<main>': undefined method `to_money' for 1:Fixnum (NoMethodError)

**Comment by spundun** [comment]
I had to add a `require 'monetize'` statement to make it work. It worked then. Feel free to close this issue, or close it once you fix the docs

**Comment by semmons99** [comment]
how about you submit a PR to correct the docs?

**Comment by spundun** [comment]
Thanks @yinquanteo
