### ISSUE TITLE
Incorrect amount converting USD -> VND

### ISSUE THREAD

**Issue by jlarusso** [RubyMoney/google_currency#40]
I'm missing a few decimal places when converting from US dollars to Vietnamese Dong.

```ruby
irb(main):001:0> usd = Money.new(50, 'USD')
=> #<Money fractional:50 currency:USD>
irb(main):002:0> vnd = usd.exchange_to('VND')
=> #<Money fractional:10902 currency:VND>
irb(main):003:0> vnd.to_i
=> 10902
```
The google finance converter shows `50 USD = 1090250 VND`

Could this be a bug?

**Comment by semmons99** [comment]
My guess, Google is using a different size subunit than is used in physical transactions, much this this ticket: https://github.com/RubyMoney/google_currency/issues/38

Perhaps you can research and submit a similar patch.
