### ISSUE TITLE
Issue while converting from Indonesian currency to British Pound

### ISSUE THREAD

**Issue by sachin87** [RubyMoney/google_currency#41]
I tried using google currency converter its giving me error while converting currency from Indonesian rupee(IDR) to British pound(GBP).

```ruby
subunit_to_unit = Money.new(1, "GBP").currency.subunit_to_unit
=> 100
Money.new(0*subunit_to_unit, 'IDR').exchange_to("GBP")
*** Money::Bank::UnknownRate Exception: Money::Bank::UnknownRate
```

Thanks for help

**Comment by yinquanteo** [comment]
This library uses Google Finance Converter under the hood. 

Looks like Google does not return an exchange rate for IDR and GBP. https://www.google.com/finance/converter

**Comment by sachin87** [comment]
can i get a list of currencies that are convertible from one current currency.
Example: in the above case if IDR cannot be converted to GBP so i need list of currencies out of
Money::Currency.all, i.e. all currencies except GBP?

**Comment by semmons99** [comment]
Unfortunately that's at the discretion of the underlying service. You could figure it out and then write a patch.
