### ISSUE TITLE
Service moved error

### ISSUE THREAD

**Issue by rebelvc** [RubyMoney/google_currency#57]
irb(main):025:0> uri = URI 'https://www.google.com/finance/converter?a=1&from=USD&to=BRL'
=> #<URI::HTTPS:0x000000057154f8 URL:https://www.google.com/finance/converter?a=1&from=USD&to=BRL>
irb(main):026:0> Net::HTTP.get(uri)
=> "<HTML><HEAD><meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\n<TITLE>302 Moved</TITLE></HEAD><BODY>\n<H1>302 Moved</H1>\nThe document has moved\n<A HREF=\"https://finance.google.com/finance/converter\">here</A>.\r\n</BODY></HTML>\r\n"

**Comment by xinranxiao** [comment]
can we bump the gem version to include https://github.com/RubyMoney/google_currency/commit/fa6e8ba366c0b63f8583e7ec7675f47d8ee7c410

**Comment by gonace** [comment]
Is it possible to get this merged soon? :)

**Comment by antstorm** [comment]
#56 solves this. I've also just pushed an update — https://rubygems.org/gems/google_currency
