### ISSUE TITLE
Money::Bank::GoogleCurrencyFetchError

### ISSUE THREAD

**Issue by hudakh** [RubyMoney/google_currency#59]
We are getting an error today
`Money::Bank::GoogleCurrencyFetchError (Money::Bank::GoogleCurrencyFetchError)`
Not sure if it's something you can fix! But I'd appreciate any feedback.

```irb(main):008:0> Money.us_dollar(100).exchange_to("CAD")
Money::Bank::GoogleCurrencyFetchError: Money::Bank::GoogleCurrencyFetchError
        from /.../google_currency-3.2.0/lib/money/bank/google_currency.rb:160:in `extract_rate'
        from /.../google_currency-3.2.0/lib/money/bank/google_currency.rb:129:in `fetch_rate'
        from /.../google_currency-3.2.0/lib/money/bank/google_currency.rb:99:in `block in get_rate'
        from /.../google_currency-3.2.0/lib/money/bank/google_currency.rb:98:in `synchronize'
        from /.../google_currency-3.2.0/lib/money/bank/google_currency.rb:98:in `get_rate'
        from /.../money-6.5.1/lib/money/bank/variable_exchange.rb:92:in `exchange_with'
        from /.../money-6.5.1/lib/money/money.rb:412:in `exchange_to'```

**Comment by hudakh** [comment]
seems like updating to version 3.4.0 fixes this! only had this issue today in Australia!

**Comment by antstorm** [comment]
Yeah, seems like it takes a bit of time to propagate across the world :)

**Comment by kaushal-kishor** [comment]
Issue now again occurring 
Money::Bank::GoogleCurrencyFetchError: Money::Bank::GoogleCurrencyFetchError

**Comment by hudakh** [comment]
@kaushal-kishor this is different.. it seems like the Google Currency API is no longer working. Refer to <https://github.com/RubyMoney/google_currency/issues/65>
