### ISSUE TITLE
I believe the site has been removed, so the API does not work anymore

### ISSUE THREAD

**Issue by mowcom** [RubyMoney/google_currency#66]
Below is how the API get's its currency conversions. It replaces GBP & USD with whatever currencies you choose. Unfortunately this site no longer exists. 

https://finance.google.com/finance/converter?a=1&from=GBP&to=USD&meta=ei%3DwoeZWqDCHsGFjAHt85ioAw

**Comment by kriskhaira** [comment]
It's been a known issue for a week. See:
https://github.com/RubyMoney/google_currency/issues/65

**Comment by sealabcore** [comment]
I am seeing this as well, how are people working around this issue?

**Comment by kriskhaira** [comment]
I linked to the issue in my last comment. People have already been discussing solutions in there: **https://github.com/RubyMoney/google_currency/issues/65**

**Comment by antstorm** [comment]
Duplicate issue, closing this thread in favour of #65
