### ISSUE TITLE
Money::Bank::GoogleCurrencyFetchError: Money::Bank::GoogleCurrencyFetchError

### ISSUE THREAD

**Issue by dieuit07** [RubyMoney/google_currency#67]
Event I upgrade version to 3.4  . I still get this bug. And It just happen in today
Is there any way to fix or work around this bug?

**Comment by kriskhaira** [comment]
It's been a known issue for a week. See https://github.com/RubyMoney/google_currency/issues/65

**Comment by sealabcore** [comment]
I am seeing this as well, how are people working around this issue?

**Comment by kriskhaira** [comment]
I linked to the issue in my last comment. People have already been discussing solutions in there: **https://github.com/RubyMoney/google_currency/issues/65**
