### ISSUE TITLE
Google discontinued their currency converter page

### ISSUE THREAD

**Issue by cianmce** [RubyMoney/google_currency#70]
This Gem no longer works as Google discontinued their currency converter page
They just redirect to a search for _finance_

```bash
$ curl "http://finance.google.com/finance/converter?a=1&from=USD&to=EUR"
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="http://www.google.com/search?q=finance">here</A>.
</BODY></HTML>
```

**Comment by cianmce** [comment]
As seen in this gif of the old cached page, google no redirects you to a search for finance
![google_finance](https://user-images.githubusercontent.com/4098222/37834923-df56c41e-2ea6-11e8-9610-1d2e2590d1a4.gif)

**Comment by antstorm** [comment]
Currently discussed in #65
